http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  loyalty:
    host: localhost
    paths: '/v1/loyalty'
  campaign:
    host: localhost
    paths: '/v1/campaign'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  loyaltyService:
    url: 'https://mvxf4gn5-3000.inc1.devtunnels.ms/'
  campaignService:
    url: 'localhost:5000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  loyaltyPipeline:
    apiEndpoints:
      - loyalty
    policies:
      - proxy:
          - action:
              serviceEndpoint: loyaltyService
              changeOrigin: true
  campaignPipeline:
    apiEndpoints:
      - campaign
    policies:
      - proxy:
          - action:
              serviceEndpoint: campaignService
              changeOrigin: true
