http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  loyalty:
    host: localhost
    paths: "/v1/loyalty"
  campaign:
    host: localhost
    paths: "/v1/campaign"
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  google:
    url: "www.google.co.in"
  loyaltyService:
    url: "https://mvxf4gn5-3000.inc1.devtunnels.ms/"
  campaignService:
    url: "https://mvxf4gn5-5000.inc1.devtunnels.ms/"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - request-transformer

pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  google:
    apiEndpoints:
      - google
    policies:
      - proxy:
          - action:
              serviceEndpoint: google
              changeOrigin: true
  loyaltyPipeline:
    apiEndpoints:
      - loyalty
    policies:
      - request-transformer:
          - action:
              headers:
                add:
                  x-tocken: "'tocken1'"
      - proxy:
          - action:
              serviceEndpoint: loyaltyService
              changeOrigin: true
  campaignPipeline:
    apiEndpoints:
      - campaign
    policies:
      - proxy:
          - action:
              serviceEndpoint: campaignService
              changeOrigin: true
